DA and DS Tools are
NumPY: Dimentionality
Pandas: data manipulation
Matplotlib : Exploratory Data Analysis
Seaborn : Advanced Exploratory Data Analysis

** NumPY**

it stands Numerical Python.
import numpy as np

NumPy function are

-array
-reshape
-shape
-size
-reshape(-1,1) and reshape(1,-1)
-ndim
-arrange
-random-randint
-random-rand
-random-random
-random-randn
-zeros
-ones
-full
-diagonal
-diag
-eye
-concatination
-transpose
-ravel
-argmax
-argmin
-axis=1
-axis=0
-sum
-max and min
-matmul



In [ ]:
# array: which is used to create data in the form of dimension .

import numpy as np

a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a[2])

[1 2 3 4 5]
1
(5,)
5
3


In [ ]:
# 2D array

a=np.array([[10,21],[9,18]])
print(a)
print(type(a))
print('-----')
print(a.ndim)
print(a.shape)
print(a.size)
print(a[1][0])

[[10 21]
 [ 9 18]]
<class 'numpy.ndarray'>
-----
2
(2, 2)
4
9


In [ ]:
# arrange : will generate value in 1D.

a=np.arange(1,11)
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [ ]:
# convert  data 1D to 2D and 3D.

a=np.arange(1,61)
print(a)
print(a.shape) # used to find rows and coulmn .
print(a.ndim)  # used to find how many dimension
print(f'total value is :', a.size)  # used to find total how many value is there .
print('------')

b=a.reshape(10,6)  #10 rows and 6 coulmn
print(b)
print(b.ndim)

print(f'index value is :',b[4][3])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
(60,)
1
total value is : 60
------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2
index value is : 28


In [ ]:
# convert 1D to 3D

a=np.arange(1,61)
print(a)
print('------')

b=a.reshape(5,2,6)
print(b)

print(f'index value is :',b[2][1][3])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
------
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]
index value is : 34


In [ ]:
# reshape (-1,1)

a=np.array([10,20,30,40,50])
print(a)
print('--------')

b=a.reshape(-1,1)
print(b)

print(b.ndim)
print(b.shape)

[10 20 30 40 50]
--------
[[10]
 [20]
 [30]
 [40]
 [50]]
2
(5, 1)


In [ ]:
# reshape (1,-1)

a=np.array([10,20,30,40])
print(a)
print(a.shape)
print('----------')


b=a.reshape(1,-1)
print(b)
print(b.shape)
print(b.ndim)

[10 20 30 40]
(4,)
----------
[[10 20 30 40]]
(1, 4)
2


In [ ]:
# randn
import numpy as np

a=np.random.randn(3,4)
print(a)
print(type(a))

[[ 0.44704419  0.86624332 -0.27482085  0.02359766]
 [-0.63582971 -0.47709302  0.10721573 -0.92068104]
 [ 0.09474564  0.95618124 -0.52197405  1.66151723]]
<class 'numpy.ndarray'>


In [ ]:
#randint

a=np.random.randint(10,50)
print(a)
print(type(a))

14
<class 'int'>


In [ ]:
#rand

a=np.random.rand(3,4)
print(a)

print(type(a))

[[0.96039672 0.61311751 0.74801409 0.32832417]
 [0.61856451 0.70442021 0.36241522 0.44690303]
 [0.52393508 0.54630105 0.71271554 0.25576711]]
<class 'numpy.ndarray'>


In [ ]:
#random

a=np.random.random(10)
print(a)

print(type(a))

[0.240397   0.84206144 0.88720773 0.09996516 0.86775003 0.41258662
 0.45117414 0.02981044 0.99098027 0.75539617]
<class 'numpy.ndarray'>


In [ ]:
# zeros :  default data type of the numpy is float64.

a=np.zeros(3)
print(a)

[0. 0. 0.]


In [ ]:
#full

a=np.full((3,4),8)
print(a)

print(type(a))

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
<class 'numpy.ndarray'>


In [ ]:
#eye

a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# daigonal : it is used to find the daigonals.

import numpy as np

a=np.array ([[10,1,9],[2,8,4],[7,6,13]])

print(a)
print('-------')
print(np.diagonal(a))



[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]]
-------
[10  8 13]


In [7]:
# ravel : it is a function will convert n-dimension data into 1D.

a=np.array ([[10,1,9],[2,8,4],[7,6,13]])
print(a)
print('-------')

b=a.ravel()
print(b)
print(b.shape)

[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]]
-------
[10  1  9  2  8  4  7  6 13]
(9,)


In [8]:
#transpose: will convert rows to column and column to rows .

a=np.array ([[10,1,9],[2,8,4],[7,6,13]])
print(a)
print('-------')

b=a.T
print(b)

[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]]
-------
[[10  2  7]
 [ 1  8  6]
 [ 9  4 13]]


In [9]:
#concatination

a=np.array ([[10,1,9],[2,8,4],[7,6,13]])
b=np.array([[10,20,30],[1,2,3],[40,50,60]])

print(a)
print('------')

print(b)
print('------')

c=np.concatenate((a,b))

print(c)


[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]]
------
[[10 20 30]
 [ 1  2  3]
 [40 50 60]]
------
[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]
 [10 20 30]
 [ 1  2  3]
 [40 50 60]]


In [14]:
# axis=1 and axis=0
# in numpy axis=1  : rows and axis=0  : coulmn

a=np.array ([[10,1,9],[2,8,4],[7,6,13]])
print(a)
print('------')

print(np.max(a,axis=1))

print('-------')

print(np.min(a,axis=1))

print('--------')

print(np.max(a,axis=1)[0])

[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]]
------
[10  8 13]
-------
[1 2 6]
--------
10


In [15]:
a=np.array ([[10,1,9],[2,8,4],[7,6,13]])
print(a)
print('------')

print(np.max(a,axis=0))

print('-------')

print(np.min(a,axis=0))

print('--------')

print(np.max(a,axis=0)[0])

[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]]
------
[10  8 13]
-------
[2 1 4]
--------
10


In [18]:
# argmax and argmin

a=np.array ([[10,1,9],[2,8,4],[7,6,13]])
print(a)
print('------')

print(np.argmax(a))

print(np.argmin(a))



[[10  1  9]
 [ 2  8  4]
 [ 7  6 13]]
------
8
1


In [19]:
# matmul

a=np.array ([[10,1,9],[2,8,4],[7,6,13]])
b=np.array ([4,3,2])

print(np.matmul(a,b))


[61 40 72]


In [21]:
# expand_dimension

a=np.array([10,20,30,40,50])
print(a.shape)
print('-------')

b=np.expand_dims(a,axis=0)

print(b)
print(b.shape)

(5,)
-------
[[10 20 30 40 50]]
(1, 5)
